#!/bin/sh
#
# Starts config-updater
#

NAME=config-updater
DAEMON=/usr/sbin/$NAME.py
PIDFILE="/var/run/$NAME.pid"
LOGFILE="/var/log/$NAME.log"

start() {
    printf "Starting $NAME: "
    start-stop-daemon -S -q -m -p "$PIDFILE" -x /usr/bin/python3 -- -u /usr/sbin/config-updater.py >> "$LOGFILE" 2>&1 &
    echo "OK"
}

stop() {
    printf "Stopping $NAME: "
    start-stop-daemon -K -q -p "$PIDFILE"
    echo "OK"
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit $?
