#!/bin/sh
#
# Starts rnsd
#
NAME=rnsd
DAEMON=/usr/bin/$NAME
PIDFILE="/var/run/$NAME.pid"

[ -r /etc/default/rns ] && . /etc/default/rns

start() {
	LOGFILE="/mnt/rns/.reticulum/logfile"
	TEMPLOG="/var/log/rnsd.log"
	ln -sf "$TEMPLOG" "$LOGFILE"
	touch "$TEMPLOG"
	chown rns:rns "$TEMPLOG"

	printf "Starting $NAME: "
	start-stop-daemon -S -q -b -m -p "$PIDFILE" -c rns -x "$DAEMON" -- --config "$RETICULUM_CONFIG" --service

	READY_PATTERN="Started rnsd"
	MAX_CHECKS=300

	i=0
	while [ $i -lt $MAX_CHECKS ]; do
	    tail -n 1 "$TEMPLOG" 2>/dev/null | grep -q "$READY_PATTERN" && {
	    echo "RNS Ready"
	    return 0
	    }
	sleep 0.1
	i=$((i + 1))
	done

	echo "RNS Not Ready"
	return 0
}

stop() {
	printf "Stopping $NAME: "
	start-stop-daemon -K -q -p "$PIDFILE" --retry=TERM/10/KILL/5
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

