#!/bin/sh
#
# Starts nomadnet
#
NAME=nomadnet
DAEMON=/usr/bin/$NAME
PIDFILE="/var/run/$NAME.pid"

[ -r /etc/default/rns ] && . /etc/default/rns

start() {
	LOGFILE="/mnt/rns/.nomadnetwork/logfile"
	TEMPLOG="/var/log/nomadnet.log"
	ln -sf "$TEMPLOG" "$LOGFILE"
	touch "$TEMPLOG"
	chown rns:rns "$TEMPLOG"

	printf "Starting $NAME: "
	start-stop-daemon -S -q -b -m -p $PIDFILE -c rns -x $DAEMON -- --config $NOMADNET_CONFIG --rnsconfig $RETICULUM_CONFIG --daemon
	echo "OK"
}
stop() {
	printf "Stopping $NAME: "
	start-stop-daemon -K -q -p "$PIDFILE"
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

